version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/myapp
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  php:
    image: php:7.2-fpm
    volumes:
      - ./app:/var/www/myapp
      - ./php.ini:/usr/local/etc/php/php.ini
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"